### ISSUE TITLE
MGSM2Fix_v_0_6_MGS1.zip gets quarantined by Windows Defender

### ISSUE THREAD

**Issue by deWanme** [nuggslet/MGSM2Fix#9]
When I download [MGSM2Fix_v_0_6_MGS1.zip](https://github.com/nuggslet/MGSM2Fix/releases/download/v0.6/MGSM2Fix_v_0_6_MGS1.zip) from [release 0.6](https://github.com/nuggslet/MGSM2Fix/releases/tag/v0.6) the file immidiately gets quarantined by Windows Defender, this *does not* happen with previous releases tho.

![image](https://github.com/nuggslet/MGSM2Fix/assets/70025667/e4fee339-9836-4d4b-8f25-f31cef913e7e)

**Comment by brianx87** [comment]
I'm getting this now too and I've already downloaded this version once without issue.

**Comment by Noname00000001** [comment]
I just tried downloading the files on a dummy laptop and the virus scanner didn't pick anything up, yet a few days ago when I did the same, Windows Defender quarantined it immediately.

Have any progress been made on sorting this issue out, or a reason for the false positive (Since I honestly doubt it's a legit Trojan)

**Comment by nuggslet** [comment]
Hopefully fixed since v0.7? Feel free to reopen if not.
